#pragma once
namespace Yelo::Enums {
	enum render_progress {
		_render_progress_sky,
		_render_progress_objects,
		_render_progress_objects_transparent,
		_render_progress_structure,
		_render_progress_none,
	};

	enum rasterizer_vertex_shader : unsigned long
	{
		_rasterizer_vs_convolution,
		_rasterizer_vs_debug,
		_rasterizer_vs_decal,
		_rasterizer_vs_detail_object_type0,
		_rasterizer_vs_detail_object_type1,
		_rasterizer_vs_effect,
		_rasterizer_vs_effect_multitexture,
		_rasterizer_vs_effect_multitexture_screenspace,
		_rasterizer_vs_effect_zsprite,
		_rasterizer_vs_environment_diffuse_light,
		_rasterizer_vs_environment_diffuse_light_ff,
		_rasterizer_vs_environment_fog,
		_rasterizer_vs_environment_fog_screen,
		_rasterizer_vs_environment_lightmap,
		_rasterizer_vs_environment_reflection_bumped,
		_rasterizer_vs_environment_reflection_flat,
		_rasterizer_vs_environment_reflection_lightmap_mask,
		_rasterizer_vs_environment_reflection_mirror,
		_rasterizer_vs_environment_reflection_radiosity,
		_rasterizer_vs_environment_shadow,
		_rasterizer_vs_environment_specular_light,
		_rasterizer_vs_environment_specular_spot_light,
		_rasterizer_vs_environment_specular_lightmap,
		_rasterizer_vs_environment_texture,
		_rasterizer_vs_lens_flare,
		_rasterizer_vs_model_fogged,
		_rasterizer_vs_model,
		_rasterizer_vs_model_ff,
		_rasterizer_vs_model_fast,
		_rasterizer_vs_model_scenery,
		_rasterizer_vs_model_active_camouflage,
		_rasterizer_vs_model_active_camouflage_ff,
		_rasterizer_vs_model_fog_screen,
		_rasterizer_vs_model_shadow,
		_rasterizer_vs_model_zbuffer,
		_rasterizer_vs_screen,
		_rasterizer_vs_screen2,
		_rasterizer_vs_transparent_generic,
		_rasterizer_vs_transparent_generic_lit_m,
		_rasterizer_vs_transparent_generic_m,
		_rasterizer_vs_transparent_generic_object_centered,
		_rasterizer_vs_transparent_generic_object_centered_m,
		_rasterizer_vs_transparent_generic_reflection,
		_rasterizer_vs_transparent_generic_reflection_m,
		_rasterizer_vs_transparent_generic_screenspace,
		_rasterizer_vs_transparent_generic_screenspace_m,
		_rasterizer_vs_transparent_generic_viewer_centered,
		_rasterizer_vs_transparent_generic_viewer_centered_m,
		_rasterizer_vs_transparent_glass_diffuse_light,
		_rasterizer_vs_transparent_glass_diffuse_light_m,
		_rasterizer_vs_transparent_glass_reflection_bumped,
		_rasterizer_vs_transparent_glass_reflection_bumped_m,
		_rasterizer_vs_transparent_glass_reflection_flat,
		_rasterizer_vs_transparent_glass_reflection_flat_m,
		_rasterizer_vs_transparent_glass_reflection_mirror,
		_rasterizer_vs_transparent_glass_tint,
		_rasterizer_vs_transparent_glass_tint_m,
		_rasterizer_vs_transparent_meter,
		_rasterizer_vs_transparent_meter_m,
		_rasterizer_vs_transparent_plasma_m,
		_rasterizer_vs_transparent_water_opacity,
		_rasterizer_vs_transparent_water_opacity_m,
		_rasterizer_vs_transparent_water_reflection,
		_rasterizer_vs_transparent_water_reflection_m,

		_rasterizer_vertex_shader,

		_rasterizer_vs_invalid = CAST(unsigned long, NONE),
	};
};
