/*
	Yelo: Open Sauce SDK
		Halo 1 (CE) Edition

	See license\OpenSauce\Halo1_CE for specific license information
*/

#undef K_HUD_UPDATE
#define K_HUD_UPDATE 0x4AC9A0

#undef K_FIRST_PERSON_WEAPONS_UPDATE
#define K_FIRST_PERSON_WEAPONS_UPDATE 0x495190

#undef K_HUD_RENDER_NAV_POINTS_CALL
#define K_HUD_RENDER_NAV_POINTS_CALL 0x4ACAF3

#undef K_HUD_RENDER_NAV_POINT_ANCHOR_HALF_X
#define K_HUD_RENDER_NAV_POINT_ANCHOR_HALF_X 0x4B2B06

#undef K_HUD_RENDER_NAV_POINT_ANCHOR_HALF_Y
#define K_HUD_RENDER_NAV_POINT_ANCHOR_HALF_Y 0x4B2B10

#undef K_HUD_ANCHOR_SCREEN_Y
#define K_HUD_ANCHOR_SCREEN_Y 0x612264

#undef K_HUD_ANCHOR_SCREEN_HALF_X
#define K_HUD_ANCHOR_SCREEN_HALF_X 0x6128E4

#undef K_HUD_ANCHOR_SCREEN_HALF_Y
#define K_HUD_ANCHOR_SCREEN_HALF_Y 0x6128E8

#undef K_HUD_RENDER_PLAYERS_CALL
#define K_HUD_RENDER_PLAYERS_CALL 0x4ACA74

#undef K_HUD_POINT_DAMAGE_ANCHOR_WIDTH
#define K_HUD_POINT_DAMAGE_ANCHOR_WIDTH 0x4B49A9

#undef K_HUD_POINT_DAMAGE_ANCHOR_HEIGHT
#define K_HUD_POINT_DAMAGE_ANCHOR_HEIGHT 0x4B4982

#undef K_HUD_POINT_DAMAGE_ANCHOR_HALF_HEIGHT
#define K_HUD_POINT_DAMAGE_ANCHOR_HALF_HEIGHT 0x4B49C3

#undef K_HUD_POINT_DAMAGE_ANCHOR_HALF_WIDTH_PTR_0
#define K_HUD_POINT_DAMAGE_ANCHOR_HALF_WIDTH_PTR_0 0x4B499E

#undef K_HUD_POINT_DAMAGE_ANCHOR_HALF_WIDTH_PTR_1
#define K_HUD_POINT_DAMAGE_ANCHOR_HALF_WIDTH_PTR_1 0x4B495E

