/*
	Yelo: Open Sauce SDK
		Halo 1 (CE) Edition

	See license\OpenSauce\Halo1_CE for specific license information
*/

#undef K_FIRST_PERSON_WEAPON_DRAW_HOOK
#define K_FIRST_PERSON_WEAPON_DRAW_HOOK 0x4952FE

#undef K_FIRST_PERSON_WEAPON_DRAW_HOOK_RETN
#define K_FIRST_PERSON_WEAPON_DRAW_HOOK_RETN 0x495303

#undef K_COMMAND_CAMERA_SET_HOOK
#define K_COMMAND_CAMERA_SET_HOOK 0x4455AC

#undef K_COMMAND_CAMERA_SET_HOOK_RETN
#define K_COMMAND_CAMERA_SET_HOOK_RETN 0x4455B1

#undef K_RASTERIZER_D3D_CREATE_DEVICE_HOOK
#define K_RASTERIZER_D3D_CREATE_DEVICE_HOOK 0x51A992

#undef K_RASTERIZER_D3D_CREATE_DEVICE_RETN
#define K_RASTERIZER_D3D_CREATE_DEVICE_RETN 0x51A997