/*
	Yelo: Open Sauce SDK
		Halo 1 (CE) Edition

	See license\OpenSauce\Halo1_CE for specific license information
*/

#undef K_QUERY_EXITFLAG_REG_CALL
#define K_QUERY_EXITFLAG_REG_CALL 0x544B3F

#undef K_RELEASE_RESOURCES_ON_EXIT_CALL
#define K_RELEASE_RESOURCES_ON_EXIT_CALL 0x544D5E

#undef K_WINMAIN_EXCEPTION_FILTER_CALL
#define K_WINMAIN_EXCEPTION_FILTER_CALL 0x544DDF