/*
	Yelo: Open Sauce SDK
		Halo 1 (CE) Edition

	See license\OpenSauce\Halo1_CE for specific license information
*/

#undef K_RASTERIZER_DISPOSE_CALL_FROM_RASTERIZER
#define K_RASTERIZER_DISPOSE_CALL_FROM_RASTERIZER 0x51ACD0

#define K_RENDERED_TRIANGLE_ARRAY_UPGRADE_ADDRESS_11 0x555E66
#define K_RENDERED_TRIANGLE_ARRAY_UPGRADE_ADDRESS_12 0x555F46